keys:
  - cipher: chacha20-ietf-poly1305
    id: '1'
    port: 5485
    secret: Od44dLWzhf8FDfLhLawFEe
  - cipher: chacha20-ietf-poly1305
    id: '2'
    port: 5485
    secret: I1PA4WX05skldMdvUuvNII
  - cipher: chacha20-ietf-poly1305
    id: '3'
    port: 5485
    secret: vEDHxNwwmzB48cUB70iHqo
  - cipher: chacha20-ietf-poly1305
    id: '4'
    port: 5485
    secret: 0m0IqV4OzhXkTM1ecOylJc
  - cipher: chacha20-ietf-poly1305
    id: '5'
    port: 5485
    secret: kmqB0J2WwMzmCxqf6h8WDI
  - cipher: chacha20-ietf-poly1305
    id: '6'
    port: 5485
    secret: s3Y2DkGd7NGbo9ftgUynAP
  - cipher: chacha20-ietf-poly1305
    id: '7'
    port: 5485
    secret: KxPcVmnjFvS0izVuOudgGn
  - cipher: chacha20-ietf-poly1305
    id: '8'
    port: 5485
    secret: 13HFyhb7FUhpoBsgAwuDqX
  - cipher: chacha20-ietf-poly1305
    id: '9'
    port: 5485
    secret: GoH1WSK9IsLnbnTg3arjoz
  - cipher: chacha20-ietf-poly1305
    id: '10'
    port: 5485
    secret: J3fsxoYOsifvQ0YtguwTWy
  - cipher: chacha20-ietf-poly1305
    id: '11'
    port: 5485
    secret: 0o6MjiudU3z2ONg4Wx9dBd
  - cipher: chacha20-ietf-poly1305
    id: '12'
    port: 5485
    secret: FW4ADYN9in64Fi18M3gwji
  - cipher: chacha20-ietf-poly1305
    id: '13'
    port: 5485
    secret: Nnuymuf4M6XglpUG9ORoeV
  - cipher: chacha20-ietf-poly1305
    id: '14'
    port: 5485
    secret: Ew7Xbns0ASUXp87sOPvHQe
  - cipher: chacha20-ietf-poly1305
    id: '15'
    port: 5485
    secret: JvQxbu3g3OhfW1eOsOrVbP
  - cipher: chacha20-ietf-poly1305
    id: '16'
    port: 5485
    secret: JFiLfpJIDMBCSvIwHLX7gi
  - cipher: chacha20-ietf-poly1305
    id: '17'
    port: 5485
    secret: Q7OKtksDHRPm2pNbYDsJ5U
  - cipher: chacha20-ietf-poly1305
    id: '18'
    port: 5485
    secret: mLct2g32xTbjt76r6iHrjy
  - cipher: chacha20-ietf-poly1305
    id: '19'
    port: 5485
    secret: lApgJblm9ae2I1Ua6OdlPO
  - cipher: chacha20-ietf-poly1305
    id: '20'
    port: 5485
    secret: IT9sWfW9ImFnLD6dhvUO7m
  - cipher: chacha20-ietf-poly1305
    id: '21'
    port: 5485
    secret: roZR2Zn84ZPfuuN9Tbndxa
  - cipher: chacha20-ietf-poly1305
    id: '22'
    port: 5485
    secret: MaajZcaKnC5FpZiBhhHDIG
  - cipher: chacha20-ietf-poly1305
    id: '23'
    port: 5485
    secret: 0i12FDc2LxtVn0Ot53FFUn
  - cipher: chacha20-ietf-poly1305
    id: '24'
    port: 5485
    secret: 8xXtdp5YHb4GyNKc0B7xlh
  - cipher: chacha20-ietf-poly1305
    id: '25'
    port: 5485
    secret: u7q2lrtQrAWstEZC4GkKml
  - cipher: chacha20-ietf-poly1305
    id: '26'
    port: 5485
    secret: CBJdX1dJfA06LnIjU8nqWF
  - cipher: chacha20-ietf-poly1305
    id: '27'
    port: 5485
    secret: RZs1jkPWF26Co3wAxm5DkB
  - cipher: chacha20-ietf-poly1305
    id: '28'
    port: 5485
    secret: K8p2nE5tdHDD8zA31Z4qLA
  - cipher: chacha20-ietf-poly1305
    id: '29'
    port: 5485
    secret: T2FGro7UiqpfnMlsO5ZGBH
  - cipher: chacha20-ietf-poly1305
    id: '30'
    port: 5485
    secret: dkjgjHS1ivDIPsyfYSFY9I
  - cipher: chacha20-ietf-poly1305
    id: '31'
    port: 5485
    secret: EuBwocvRjsEfRkasM1Vt0J
  - cipher: chacha20-ietf-poly1305
    id: '32'
    port: 5485
    secret: l3gu7jFztxJgVL8aZI47rg
  - cipher: chacha20-ietf-poly1305
    id: '33'
    port: 5485
    secret: SR7Ym9AJYKrOdDDGSafMio
  - cipher: chacha20-ietf-poly1305
    id: '34'
    port: 5485
    secret: hjc9FTgbUoX1kRaMYQQLdb
  - cipher: chacha20-ietf-poly1305
    id: '35'
    port: 5485
    secret: ebFESgxeQIAPNu6PB1qd9g
  - cipher: chacha20-ietf-poly1305
    id: '36'
    port: 5485
    secret: HAUtikKiSo71rVM7NqcFPZ
  - cipher: chacha20-ietf-poly1305
    id: '37'
    port: 5485
    secret: jIJoaXzHpNPmyy8FJRZomt
  - cipher: chacha20-ietf-poly1305
    id: '38'
    port: 5485
    secret: eEPca0uBjZM7dfajUDnr7P
  - cipher: chacha20-ietf-poly1305
    id: '39'
    port: 5485
    secret: BKYXi1zk1J4WM2uRifZKVA
  - cipher: chacha20-ietf-poly1305
    id: '40'
    port: 5485
    secret: olXFHqZRoS4i1hPNKcFsry
  - cipher: chacha20-ietf-poly1305
    id: '41'
    port: 5485
    secret: zmoXRfEmRQmom0vrBOroVd
  - cipher: chacha20-ietf-poly1305
    id: '42'
    port: 5485
    secret: YABeBTerrvwrXULlG8rkWN
  - cipher: chacha20-ietf-poly1305
    id: '43'
    port: 5485
    secret: Svbqu4TgtWJ9irnp1avAPQ
  - cipher: chacha20-ietf-poly1305
    id: '44'
    port: 5485
    secret: gCXC1hWTCa1pMGNNHM1Anm
  - cipher: chacha20-ietf-poly1305
    id: '45'
    port: 5485
    secret: 7S3HzUS1kea1hsY4v3YE9x
  - cipher: chacha20-ietf-poly1305
    id: '46'
    port: 5485
    secret: lgVH2BCAkjlEHQnB52hI7r
  - cipher: chacha20-ietf-poly1305
    id: '47'
    port: 5485
    secret: dWODuqf9ysewblnssxhNAh
  - cipher: chacha20-ietf-poly1305
    id: '48'
    port: 5485
    secret: L4u9iWOfVhh3JQVgWWCbwJ
  - cipher: chacha20-ietf-poly1305
    id: '49'
    port: 5485
    secret: 3UiQBc8tiwA5aTSCHwWqXu
  - cipher: chacha20-ietf-poly1305
    id: '50'
    port: 5485
    secret: Kd8luHAT1gkxGscfZ4lX87
